#!/usr/bin/env python3
"""
tools/gen_rom_embed.py
Converts a binary ROM file into a C source file containing an embedded byte array.
The array is placed in the .rom_data ELF section (read-only, outside the heap).

Usage:
    python3 tools/gen_rom_embed.py <input.bin> > bare-metal/kernel/rom_embed.c
"""

import sys
import os

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <rom.bin>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    with open(path, "rb") as f:
        data = f.read()

    name = os.path.basename(path).replace(".", "_").replace("-", "_")
    size = len(data)

    print("/* Auto-generated by tools/gen_rom_embed.py -- do not edit */")
    print("#include <stdint.h>")
    print()
    print('__attribute__((section(".rom_data")))')
    print(f"const uint8_t embedded_rom[{size}] = {{")

    # 16 bytes per line
    for i in range(0, size, 16):
        chunk = data[i:i+16]
        print("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")

    print("};")
    print()
    print(f"const uint32_t embedded_rom_size = {size}u;")

if __name__ == "__main__":
    main()
